export const INDUSTRIES = [
    'Software Development',
    'Web Development',
    'Mobile Development',
    'Data Science',
    'Machine Learning',
    'Artificial Intelligence',
    'DevOps',
    'Cloud Computing',
    'Networking',
    'Cybersecurity',
    'Database Administration',
    'UI/UX Design',
    'Product Management',
    'Quality Assurance',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Civil Engineering',
    'Chemical Engineering',
    'Aerospace Engineering',
    'Biomedical Engineering',
    'Other'
  ];
  export const POPULAR_COMPANIES = [
    'Google',
    'Microsoft',
    'Amazon',
    'Apple',
    'Facebook',
    'Netflix',
    'Tesla',
    'IBM',
    'Intel',
    'Oracle',
    'Salesforce',
    'Adobe',
    'Twitter',
    'Uber',
    'Airbnb',
    'LinkedIn',
    'Spotify',
    'Atlassian',
    'Shopify',
    'Slack'
  ];